apiVersion: apps/v1
kind: Deployment
metadata:
  name: huggingface-pipeline-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huggingface-pipeline-webserver
  template:
    metadata:
      labels:
        app: huggingface-pipeline-webserver
    spec:
      nodeName: sm02
      containers:
      - name: server
        image: tsz.io/xyx/pipeline-webserver:20230616
        args:
          - --host=0.0.0.0
        env:
          - name: MODEL_PATH
            value: "/data/llama-7b"
        ports:
          - containerPort: 8000
        resources:
          limits:
            cpu: 4
            memory: 64Gi
            nvidia.com/gpu: 1
        volumeMounts:
          - mountPath: /data
            name: data
          - mountPath: /dev/shm
            name: dshm
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: chat
        - name: dshm
          emptyDir:
            medium: Memory
