FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

RUN pip install --no-cache-dir --upgrade pip && \
  pip install --no-cache-dir --default-timeout=100 fschat

COPY openai.sh .

ENTRYPOINT [ "./openai.sh" ]
