apiVersion: tensorstack.dev/v1beta1
kind: SimpleMLService
metadata:
  name: fastchat-openai
spec:
  replicas: 1
  scheduler:
    t9kScheduler:
      queue: default
  storage:
    pvc:
      name: chatglm2-6b
      containerPath: /workspace/chatglm2-6b
  service:
    type: ClusterIP
    ports:
    - targetPort: 8000
      port: 8000
  custom:
    spec:
      containers:
      - name: server
        image: t9kpublic/fastchat-openai:20230628
        args:
          - "./chatglm2-6b"
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 4
            memory: 64Gi
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
