apiVersion: tensorstack.dev/v1beta1
kind: SimpleMLService
metadata:
  name: triton-huggingface
spec:
  replicas: 1
  scheduler:
    t9kScheduler:
      queue: default
  service:
    type: ClusterIP
    ports:
    - targetPort: 8000
      port: 8000
  custom:
    spec:
      containers:
      - name: server
        image: tsz.io/xyx/triton-huggingface:test-v1
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 1
            memory: 16Gi
            nvidia.com/gpu: 1
        volumeMounts:
          - mountPath: /data/vit-base-patch16-224-in21k
            name: data
            subPath: vit-base-patch16-224-in21k
          - mountPath: /models
            name: data
            subPath: python_model_repository
          - mountPath: /dev/shm
            name: dshm
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: draw
        - name: dshm
          emptyDir:
            medium: Memory
